#pragma once

#include <fmt/printf.h>

#include <vtkAppendPolyData.h>
#include <vtkCellArray.h>
#include <vtkCellData.h>
#include <vtkDataArray.h>
#include <vtkDepthSortPolyData.h>
#include <vtkFloatArray.h>
#include <vtk_jpeg.h>
#include <vtkLookupTable.h>
#include <vtkMassProperties.h>
#include <vtkObject.h>
#include <vtkPLYWriter.h>
#include <vtk_png.h>
#include <vtkPointData.h>
#include <vtkPoints.h>
#include <vtkPolyData.h>
#include <vtkPolyDataNormals.h>
#include <vtkPolyDataWriter.h>
#include <vtkStripper.h>
#include <vtkTriangleFilter.h>
#include <vtkVersionMacros.h>

#include <wx/busyinfo.h>
#include <wx/button.h>
#include <wx/colordlg.h>
#include <wx/colour.h>
#include <wx/dcclient.h>
#include <wx/dialog.h>
#include <wx/dirdlg.h>
#include <wx/display.h>
#include <wx/dnd.h>
#include <wx/docview.h>
#include <wx/fileconf.h>
#include <wx/filedlg.h>
#include <wx/filename.h>
#include <wx/frame.h>
#include <wx/fs_zip.h>
#include <wx/gbsizer.h>
#include <wx/glcanvas.h>
#include <wx/help.h>
#include <wx/html/helpctrl.h>
#include <wx/checkbox.h>
#include <wx/choice.h>
#include <wx/image.h>
#include <wx/intl.h>
#include <wx/listbox.h>
#include <wx/menu.h>
#include <wx/minifram.h>
#include <wx/msgdlg.h>
#include <wx/panel.h>
#include <wx/progdlg.h>
#include <wx/radiobox.h>
#include <wx/radiobut.h>
#include <wx/slider.h>
#include <wx/spinctrl.h>
#include <wx/statbmp.h>
#include <wx/statbox.h>
#include <wx/statline.h>
#include <wx/stattext.h>
#include <wx/strconv.h>
#include <wx/string.h>
#include <wx/textctrl.h>
#include <wx/timer.h>
#include <wx/toolbar.h>
#include <wx/treectrl.h>
#include <wx/txtstrm.h>
#include <wx/utils.h>
#include <wx/valgen.h>
#include <wx/valtext.h>
#include <wx/wfstream.h>
#include <wx/window.h>
#include <wx/xml/xml.h>

#include <algorithm>
#include <any>
#include <cassert>
#include <cctype>
#include <clocale>
#include <cmath>
#include <csetjmp>
#include <cstddef>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <limits>
#include <list>
#include <map>
#include <set>
#include <string_view>
#include <string>
#include <vector>
