name: cmake
on: 
  push:
    branches:
      - cmake
  pull_request:
    branches:
      - cmake
jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
        type: [Debug, Release]
        sanitizer: ["", address]
        compiler: 
          - { cc: gcc,   cxx: g++     }
          - { cc: clang, cxx: clang++ }
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y texlive-binaries texlive-metapost libproj-dev libwxgtk3.0-gtk3-dev libvtk7-dev survex imagemagick ghostscript ninja-build
      - run: |
          mkdir build && cd build && \
          cmake -G Ninja \
                -DCMAKE_BUILD_TYPE=${{ matrix.type }} \
                -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
                -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }} \
                -DECM_ENABLE_SANITIZERS=${{ matrix.sanitizer }} ..
      - run: cmake --build build
      - run: cmake --build build -t test

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        config:
          - { msystem: MINGW64, arch: x86_64 }
          - { msystem: MINGW32, arch: i686   }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.config.msystem }}
          update: true
          install: make git mingw-w64-${{ matrix.config.arch }}-cmake mingw-w64-${{ matrix.config.arch }}-proj mingw-w64-${{ matrix.config.arch }}-vtk mingw-w64-${{ matrix.config.arch }}-wxWidgets mingw-w64-${{ matrix.config.arch }}-gcc mingw-w64-${{ matrix.config.arch }}-make mingw-w64-${{ matrix.config.arch }}-bwidget
      - run: mkdir build && cd build && cmake -G "MSYS Makefiles" ..
      - run: cmake --build build -t therion loch utest -- -j 4
