name: cmake
on: 
  push:
    branches:
      - cmake
  pull_request:
    branches:
      - cmake
jobs:
  cmake-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y texlive-binaries texlive-metapost libproj-dev libwxgtk3.0-gtk3-dev libvtk7-dev survex imagemagick ghostscript ninja-build
      - run: mkdir build && cd build && cmake -G Ninja .. && ninja && ninja test
