name: cmake
on: 
  push:
    branches:
      - cmake
  pull_request:
    branches:
      - cmake
jobs:
  linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y texlive-binaries texlive-metapost libproj-dev libwxgtk3.0-gtk3-dev libvtk7-dev survex imagemagick ghostscript ninja-build
      - run: mkdir build && cd build && cmake -G Ninja .. && ninja && ninja test

  windows:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          update: true
          install: mingw-w64-x86_64-cmake mingw-w64-x86_64-proj mingw-w64-x86_64-vtk mingw-w64-x86_64-wxWidgets mingw-w64-x86_64-gcc mingw-w64-x86_64-make mingw-w64-x86_64-bwidget
      - run: mkdir build && cd build && /mingw64/bin/cmake -G "MSYS Makefiles" ..
      - run: |
          set MSYSTEM=MINGW64
          msys2 -c '/mingw64/bin/cmake --build . -t therion loch utest -- -j 4'
