name: cmake
on: 
  push:
    branches:
      - cmake
  pull-request:
    branches:
      - cmake
jobs:
  cmake-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install -y texlive-binaries texlive-metapost libproj-dev libwxgtk3.0-gtk3-dev libvtk7-dev survex imagemagick ghostscript
      - run: mkdir build && cd build
      - run: cmake ..
      - run: make -j4
      - run: make test
